spring.application.name=auth-service

management.endpoint.health.show-details=always

spring.datasource.url=jdbc:postgresql://auth-db:5432/devdb
spring.datasource.username=userdev
spring.datasource.password=userdevkey
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

app.jwt.secret=9a4fdbd3d6d5adb9701d4734054b4287311749832a884848d7c2f6d78707166e
app.jwt.expiration-ms=86400000