ALTER TABLE users ALTER COLUMN password DROP NOT NULL;

ALTER TABLE users ADD COLUMN provider_id VARCHAR(255) NULL;

ALTER TABLE users ADD COLUMN auth_provider VARCHAR(50) NOT NULL DEFAULT 'LOCAL';

ALTER TABLE users ALTER COLUMN auth_provider DROP DEFAULT;